services:
  - type: web
    name: gym-planner-backend
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      # Questa variabile temporanea prende l'URL ESTERNO dal database di Render
      - key: RENDER_EXTERNAL_URL
        fromDatabase:
          name: gym-planner-db
          property: externalConnectionString

      # QUESTA È LA CHIAVE: Creiamo l'URL corretto per Java
      # aggiungendo "jdbc:" davanti all'URL di Render.
      - key: SPRING_DATASOURCE_URL
        value: jdbc:${RENDER_EXTERNAL_URL}

      # Impostiamo le altre proprietà di Spring qui, per massima sicurezza
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"