# In render.yaml, dentro la sezione 'services:'

envVars:
  - key: DB_HOST
    fromDatabase:
      name: gym-planner-db # Assicurati che il nome del DB sia corretto
      property: host
  - key: DB_PORT
    fromDatabase:
      name: gym-planner-db
      property: port
  - key: DB_DATABASE
    fromDatabase:
      name: gym-planner-db
      property: database
  - key: DB_USERNAME
    fromDatabase:
      name: gym-planner-db
      property: user
  - key: DB_PASSWORD
    fromDatabase:
      name: gym-planner-db
      property: password