services:
  # Questa è la configurazione per il nostro Web Service
  - type: web
    name: gym-planner-backend
    env: java
    plan: free # Specifichiamo il piano gratuito
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/gym-planner-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: gym-planner-db # Il nome del database che hai creato su Render
          property: internalUrl
      - key: DB_USERNAME
        fromDatabase:
          name: gym-planner-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gym-planner-db
          property: password