services:
  - type: web
    name: gym-planner-backend
    # CORREZIONE 1: Abbiamo rimosso la riga 'runtime: java'.
    plan: free
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/gym-planner-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    envVars:
      # CORREZIONE 2: Forniamo le parti della connessione al DB separatamente
      - key: DB_HOST
        fromDatabase:
          name: gym-planner-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gym-planner-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gym-planner-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gym-planner-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gym-planner-db
          property: password