services:
  - type: web
    name: gym-planner-backend
    runtime: java # <-- CORREZIONE 1: 'runtime' invece di 'env'
    plan: free
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/gym-planner-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: gym-planner-db
          property: internalConnectionString # <-- CORREZIONE 2
      - key: DB_USERNAME
        fromDatabase:
          name: gym-planner-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gym-planner-db
          property: password